#!/bin/bash
set -euo pipefail
exec > >(tee /var/log/startup-script.log | logger -t startup-script -s 2>/dev/console) 2>&1

echo "=== ClearSettle VM Bootstrap [$(date)] ==="

# ── 1. System packages ─────────────────────────────────────────────────────────
apt-get update -y
apt-get install -y \
  ca-certificates curl gnupg lsb-release \
  htop vim git jq unzip \
  certbot python3-certbot-nginx \
  fail2ban ufw

# ── 2. Docker CE ───────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi

systemctl enable docker
systemctl start docker

# ── 3. Google Cloud Ops Agent (logging + monitoring) ──────────────────────────
if ! command -v google-cloud-ops-agent &>/dev/null; then
  curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
  bash add-google-cloud-ops-agent-repo.sh --also-install
  rm -f add-google-cloud-ops-agent-repo.sh
fi

# ── 4. Application directory ───────────────────────────────────────────────────
APP_DIR="/opt/clearsettle"
mkdir -p "$APP_DIR"/{nginx/ssl,logs,uploads,backups}
chmod 750 "$APP_DIR"

# deploy user for CI/CD (non-root)
if ! id deploy &>/dev/null; then
  useradd -m -s /bin/bash -G docker deploy
fi

# ── 5. Authenticate Docker with Artifact Registry ─────────────────────────────
gcloud auth configure-docker ${region}-docker.pkg.dev --quiet

# ── 6. Load secrets from Secret Manager ───────────────────────────────────────
get_secret() {
  gcloud secrets versions access latest --secret="$1" --project="${project_id}" 2>/dev/null || echo ""
}

SECRET_KEY=$(get_secret "clearsettle-${env}-secret-key")
DB_PASSWORD=$(get_secret "clearsettle-${env}-db-password")
ENCRYPTION_KEY=$(get_secret "clearsettle-${env}-encryption-key")
SP_API_CLIENT_ID=$(get_secret "clearsettle-${env}-sp-api-client-id")
SP_API_CLIENT_SECRET=$(get_secret "clearsettle-${env}-sp-api-client-secret")

# Write env file (only root-readable)
cat > "$APP_DIR/.env.prod" <<EOF
# Auto-generated by startup script — do not edit manually
ENV=${env}
PROJECT_ID=${project_id}
REGISTRY=${registry}
IMAGE_TAG=latest

# Database
DATABASE_URL=postgresql+asyncpg://clearsettle:$${DB_PASSWORD}@${db_host}:5432/clearsettle

# Security
SECRET_KEY=$${SECRET_KEY}
ENCRYPTION_KEY=$${ENCRYPTION_KEY}

# Amazon SP-API
SP_API_CLIENT_ID=$${SP_API_CLIENT_ID}
SP_API_CLIENT_SECRET=$${SP_API_CLIENT_SECRET}
SP_API_ENDPOINT=https://sellingpartnerapi-eu.amazon.com
SP_API_REDIRECT_URI=https://${domain}/api/sp-api/callback
FRONTEND_URL=https://${domain}

# CORS
ALLOWED_ORIGINS=https://${domain}
EOF
chmod 600 "$APP_DIR/.env.prod"

# ── 7. NGINX base config ───────────────────────────────────────────────────────
# The full nginx.prod.conf will be deployed by CI/CD.
# This baseline config serves HTTP and allows Certbot to verify the domain.
cat > /etc/nginx/sites-available/clearsettle <<'NGINX_EOF'
server {
    listen 80;
    server_name ${domain};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
NGINX_EOF
ln -sf /etc/nginx/sites-available/clearsettle /etc/nginx/sites-enabled/clearsettle
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx 2>/dev/null || systemctl start nginx

# ── 8. fail2ban (SSH brute-force protection) ──────────────────────────────────
cat > /etc/fail2ban/jail.local <<'F2B'
[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 5

[sshd]
enabled = true
port    = ssh
logpath = %(sshd_log)s
F2B
systemctl enable fail2ban
systemctl restart fail2ban

# ── 9. Automated DB backup cron ───────────────────────────────────────────────
cat > /opt/clearsettle/scripts/db-backup.sh <<'BACKUP_EOF'
#!/bin/bash
set -euo pipefail
BACKUP_DIR="/opt/clearsettle/backups"
DATE=$(date +%Y%m%d_%H%M%S)
DB_PASS=$(gcloud secrets versions access latest --secret="clearsettle-${env}-db-password" --project="${project_id}")
PGPASSWORD="$DB_PASS" pg_dump \
  -h "${db_host}" -U clearsettle -d clearsettle \
  -Fc > "$BACKUP_DIR/clearsettle_$DATE.dump"
# Keep last 30 backups
ls -t "$BACKUP_DIR"/*.dump | tail -n +31 | xargs -r rm
# Upload to GCS
gsutil cp "$BACKUP_DIR/clearsettle_$DATE.dump" \
  "gs://${project_name}-${env}-backups/db/clearsettle_$DATE.dump"
echo "Backup complete: clearsettle_$DATE.dump"
BACKUP_EOF
chmod +x /opt/clearsettle/scripts/db-backup.sh

# Daily backup at 02:00 UTC
echo "0 2 * * * root /opt/clearsettle/scripts/db-backup.sh >> /var/log/db-backup.log 2>&1" \
  > /etc/cron.d/clearsettle-backup

# ── 10. Cleanup ───────────────────────────────────────────────────────────────
chown -R deploy:deploy /opt/clearsettle
apt-get autoremove -y
apt-get clean

echo "=== Bootstrap complete [$(date)] ==="
